- name: Add host to known_hosts
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan {{ ansible_host }}') }}"
    hash_host: true
  retries: 10
  delay: 10
  register: result
  until: result.failed == false
  delegate_to: proxmox
- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:
    timeout: 120
- name: Gather Facts about hosts
  ansible.builtin.gather_facts: