all:
  hosts:
    cloudflared:
      ansible_user: root
      ansible_host: 192.168.1.36
      type: lxc
      metrics: true
      cores: 1
      memory: 512
      swap: 512
      mount_points:
      storage: "zfs-hdd"
      disk_size: 2
      unprivileged: false
      vmid: 100
    loud:
      ansible_user: root
      ansible_host: 192.168.1.236
      type: physical
      metrics: false

    file-server:
      vmid: 101
      ansible_user: root
      ansible_host: 192.168.1.17
      type: lxc
      metrics: true
      cores: 1
      memory: 512
      swap: 512
      mount_points:
        - src: /primary/archive
          target: /primary/archive
        - src: /primary/media
          target: /primary/media
        - src: /primary/backups
          target: /primary/backups
        - src: /primary/geocoder
          target: /primary/geocoder
        - src: /primary/lauren
          target: /primary/lauren
        - src: /primary/lake
          target: /primary/lake
        - src: /primary/dropbox
          target: /primary/dropbox
        - src: /primary/s3
          target: /primary/s3
      storage: "zfs-ssd"
      disk_size: 2
      unprivileged: false
    geocoder-lxc:
      vmid: 103
      ansible_user: root
      ansible_host: 192.168.1.201
      type: lxc
      metrics: true
      cores: 4
      memory: 8192
      swap: 512
      mount_points:
        - src: /primary/geocoder
          target: /primary/geocoder
      storage: "local-lvm"
      disk_size: 24
      unprivileged: false
    plex:
      ansible_user: root
      ansible_host: 192.168.1.13
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true
      cores: 2
      memory: 8192
      swap: 512
      mount_points:
        - src: /primary/media
          target: /primary/media
      storage: "zfs-ssd"
      disk_size: 72
      unprivileged: false
      vmid: 600
    plex-dev:
      ansible_user: root
      ansible_host: 192.168.1.14
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true
      vmid: 600
      cores: 2
      memory: 8192
      swap: 512
      mount_points:
        - src: /primary/media
          target: /primary/media
      storage: "zfs-ssd"
      disk_size: 72
      unprivileged: false

    monitoring:
      vmid: 800
      ansible_user: root
      ansible_host: 192.168.1.200
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true
      cores: 4
      memory: 2048
      swap: 0
      mount_points:
      storage: "zfs-ssd"
      disk_size: 20
      unprivileged: false

    greatlakes-db:
      ansible_user: micah
      ansible_become: true
      ansible_host: 192.168.1.56
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: qemu
      metrics: true
      postgres_exporter_password: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      postgres_exporter_username: postgres

    development:
      ansible_connection: local
      ansible_user: micah
      ansible_host: 192.168.1.61
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: qemu
      metrics: true

    proxmox:
      ansible_host: 192.168.1.47
      ansible_user: root
      type: physical
      metrics: true
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      cleanup_script_path: "/root/scripts/cleanup_s3.sh"
      hook_script_path: "/root/scripts/hook_script.pl"
      host_backup_script_path: "/root/scripts/backup_host.sh"

    rescue:
      ansible_host: 192.168.1.43
      ansible_become: true
      ansible_user: micah
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      node_exporter_arch: arm64
      type: physical
      metrics: true

    k3s1:
      ansible_host: 192.168.1.230
      ansible_user: root
      vmid: 701
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    k3s2:
      ansible_host: 192.168.1.231
      ansible_user: root
      vmid: 702
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    k3s3:
      ansible_user: root
      ansible_host: 192.168.1.232
      vmid: 703
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true
    k3s4:
      ansible_user: root
      ansible_host: 192.168.1.233
      vmid: 704
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true
    k3snfs:
      vmid: 706
      ansible_user: root
      ansible_host: 192.168.1.235
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    homeassistant:
      ansible_host: 192.168.1.225
      metrics: false

    dream_machine:
      ansible_host: 192.168.1.1
      metrics: false

    cat_feeder:
      ansible_host: 192.168.2.116
      type: esphome
      metrics: true
    air_gradient:
      ansible_host: 192.168.2.71
      type: esphome
      metrics: true
    filament_scale:
      ansible_host: 192.168.2.219
      type: esphome
      metrics: true
    gitlab-runner:
      ansible_user: root
      ansible_host: 192.168.1.15
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true
      vmid: 300
      cores: 4
      memory: 4096
      swap: 512
      mount_points:
      storage: "zfs-ssd"
      disk_size: 50
      unprivileged: false
esphome:
  hosts:
    air_gradient:
    filament_scale:
node_metrics:
  hosts:
    k3s1:
    k3s2:
    k3s3:
    k3s4:
    k3snfs:
    rescue:
    proxmox:
    greatlakes-db:
    cloudflared:
    plex:
    geocoder-lxc:
    file-server:
    loud:

cluster:
  children:
    master:
      hosts:
        k3s1:
    node:
      hosts:
        k3s2:
        k3s3:
        k3s4:
    cluster_nfs:
      hosts:
        k3snfs:
