all:
  hosts:
    cloudflared:
      ansible_user: root
      ansible_host: 192.168.1.36
      type: lxc
      metrics: true

    loud:
      ansible_user: root
      ansible_host: 192.168.1.236
      type: physical
      metrics: false

    file-server:
      ansible_user: root
      ansible_host: 192.168.1.17
      type: lxc
      metrics: true

    geocoder-lxc:
      ansible_user: root
      ansible_host: 192.168.1.201
      type: lxc
      metrics: true

    plex:
      ansible_user: root
      ansible_host: 192.168.1.13
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true

    monitoring:
      vmid: 800
      ansible_user: root
      ansible_host: 192.168.1.200
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true

    gitlab-runner:
      ansible_user: root
      ansible_host: 192.168.1.204
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      type: lxc
      metrics: true

    docker:
      ansible_user: root
      ansible_host: 192.168.1.139
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    greatlakes-db:
      ansible_user: micah
      ansible_become: true
      ansible_host: 192.168.1.56
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: qemu
      metrics: true
      postgres_exporter_password: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      postgres_exporter_username: postgres

    development:
      ansible_connection: local
      ansible_user: micah
      ansible_host: 192.168.1.61
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: qemu
      metrics: true

    proxmox:
      ansible_host: 192.168.1.47
      ansible_user: root
      type: physical
      metrics: true
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5') }}"
      cleanup_script_path: "/root/scripts/cleanup_s3.sh"
      hook_script_path: "/root/scripts/hook_script.pl"
      host_backup_script_path: "/root/scripts/backup_host.sh"

    rescue:
      ansible_host: 192.168.1.43
      ansible_become: true
      ansible_user: micah
      ansible_sudo_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      node_exporter_arch: arm64
      type: physical
      metrics: true

    k3s1:
      ansible_host: 192.168.1.230
      ansible_user: root
      vmid: 701
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    k3s2:
      ansible_host: 192.168.1.231
      ansible_user: root
      vmid: 702
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    k3s3:
      ansible_user: root
      ansible_host: 192.168.1.232
      vmid: 703
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    k3snfs:
      vmid: 706
      ansible_user: root
      ansible_host: 192.168.1.235
      ansible_ssh_pass: "{{ lookup('bitwarden.secrets.lookup', 'c59e4eef-9ffb-4ba8-8797-b202013a47d5', state_file_dir=bitwarden_state_dir) }}"
      type: lxc
      metrics: true

    homeassistant:
      ansible_host: 192.168.1.225
      metrics: false

    dream_machine:
      ansible_host: 192.168.1.1
      metrics: false
node_metrics:
  hosts:
    k3s1:
    k3s2:
    k3s3:
    k3snfs:
    rescue:
    proxmox:
    greatlakes-db:
    docker:
    cloudflared:
    gitlab-runner:
    plex:
    geocoder-lxc:
    file-server:
    loud:

cluster:
  children:
    master:
      hosts:
        k3s1:
    node:
      hosts:
        k3s2:
        k3s3:
    cluster_nfs:
      hosts:
        k3snfs:
