import enum


class GrandPrix(enum.Enum):
    ABU_DHABI = "Abu Dhabi"
    AUSTRALIA = "Australia"
    AUSTRIA = "Austria"
    AZERBAIJAN = "Azerbaijan"
    BAHRAIN = "Bahrain"
    BELGIUM = "Belgium"
    BRAZIL = "Brazil"
    CANADA = "Canada"
    CHINA = "China"
    EIFEL = "Eifel"
    EMILIA_ROMAGNA = "Emilia Romagna"
    FRANCE = "France"
    GERMANY = "Germany"
    GREAT_BRITAIN = "Great Britain"
    HUNGARY = "Hungary"
    ITALY = "Italy"
    JAPAN = "Japan"
    LAS_VEGAS = "Las Vegas"
    MEXICO = "Mexico"
    MIAMI = "Miami"
    MONACO = "Monaco"
    NETHERLANDS = "Netherlands"
    PORTUGAL = "Portugal"
    QATAR = "Qatar"
    RUSSIA = "Russia"
    SAKHIR = "Sakhir"
    SAUDI_ARABIA = "Saudi Arabia"
    SINGAPORE = "Singapore"
    SPAIN = "Spain"
    STEIERMARK = "Steiermark"
    STYRIA = "Styria"
    TOSCANA = "Toscana"
    TURKEY = "Turkey"
    UNITED_STATES = "United States"
    PRESEASON_TESTING = "Preseason Testing"
