- name: Install python3 and pip
  ansible.builtin.apt:
    name: 
      - python3
      - python3-pip
    state: present
- name: Install python packages
  ansible.builtin.pip:
    name:
      - requests
      - PyYAML
    state: present
    break_system_packages: true