# Configure machines (VMs and Physical)

# - hosts: proxmox
#   name: Configure machine [proxmox]
#   roles:
#     - add_to_known_hosts
#     - pve_backup

# - hosts: development
#   name: Configure machine [development]
#   become: true
#   roles:
#     - add_to_known_hosts
#   tasks:
#     - name: Install ansible
#       ansible.builtin.apt:
#         name:
#           - ansible
#           - ansible-lint
#         state: present

- hosts: master:node
  name: Configure machine(s) [cluster]
  gather_facts: false
  roles:
    - k3s_infra
    - k3s_prereq
    - k3s_download

# - hosts: cluster_nfs
#   name: Configure machine [cluster nfs]
#   gather_facts: false
#   roles:
#     - k3s_nfs_server
#     - geerlingguy.nfs

# - hosts: master
#   name: Configure machine [cluster master]
#   become: true
#   roles:
#     - k3s_install_master

# - hosts: node
#   name: Configure machine(s) [cluster nodes]
#   become: true
#   roles:
#     - k3s_install_node

# - hosts: localhost
#   connection: local
#   become: false
#   roles:
#     - k3s_postconfig

# - hosts: node_metrics
#   name: Install node-exporter
#   roles:
#     - add_to_known_hosts
#     - geerlingguy.node_exporter

# - hosts: monitoring
#   name: Configure machine(s) [monitoring]
#   gather_facts: false
#   roles:
#     - create_lxc
#     - ensure_correct_rules_file
#     - prometheus.prometheus.prometheus
#     - prometheus.prometheus.pushgateway
#     - prometheus.prometheus.alertmanager
#     - prometheus.prometheus.blackbox_exporter

# - hosts: greatlakes-db
#   roles:
#     - prometheus.prometheus.postgres_exporter
# - hosts: master
#   roles:
#     - kube_setup
- hosts: master
  roles:
    - kube_setup
    - grafana
    # - pgadmin
    # - pve_exporter
    # - unpoller
    # - sonarr
    # - radarr
    # - tautulli
    - overseer
    # - fidelity_calendar
    # - prefect_exporter
    # - greatlakes
    # - prometheus_operator
    # - prowlarr
    # - formula1
    # - jackett
    # - transmission
    # - nzbget
    # - monica
    # - magic_mirror
    # - flaresolverr
    # - nzbget_exporter
    # - transmission_exporter
    # - rtorrent
    # - chicahgo
    # - namada_exporter
    # - metabase

# # - hosts: plex
# #   gather_facts: false
# #   roles:
# #     - plex


# - hosts: github-runner-lab
#   vars:
#     github_account: mcfitz2
#     github_repo: lab
#     access_token: "{{ github_token }}"
#     runner_user: root

#   roles:
#     - create_lxc
#     - monolithprojects.github_actions_runner
#     - geerlingguy.docker
