stages:
  - lint
  - build-images
lint-compose:   
  stage: lint    
  image: sdesbure/yamllint

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    image: sdesbure/yamllint
    
  script:
    - yamllint -s docker-compose.yml

validate-compose:   # This job also runs in the test stage.
  stage: lint    # It can run at the same time as unit-test-job (in parallel).
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

  script:
    - docker-compose -f docker-compose.yml config

build-and-push:   # This job also runs in the test stage.
  stage: build-images    # It can run at the same time as unit-test-job (in parallel).
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push