# yamllint disable rule:line-length
---
version: "3.8"
services:
  oauth:
    restart: always
    image: registry.gitlab.com/mcfitz2/lab/oauth:latest
    build:
      context: ./
      dockerfile: ./oauth-service/Dockerfile
    ports:
      - 4002:4002
    environment:
      BASE_URL: "https://oauth.micahf.net"
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  uptime:
    image: registry.gitlab.com/mcfitz2/lab/uptime:latest
    restart: always
    build:
      context: ./
      dockerfile: ./uptime-service/Dockerfile
    ports:
      - 4003:4003
    environment:
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
      PREFECT_ACCOUNT_ID: '6661ec6b-f68e-42a9-bec1-fcc2b961e3c4'
      PREFECT_WORKSPACE_ID: '7e45c4b7-3704-45cc-88da-ee84c415c970'
  takeout:
    image: registry.gitlab.com/mcfitz2/lab/takeout:latest
    restart: always
    build:
      context: ./
      dockerfile: ./takeout/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  row-counts:
    image: registry.gitlab.com/mcfitz2/lab/row-counts:latest
    restart: always
    build:
      context: ./
      dockerfile: ./row_counts/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  austin-energy:
    image: registry.gitlab.com/mcfitz2/lab/austin-energy:latest
    restart: always
    build:
      context: ./
      dockerfile: ./austin_energy/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  fitbit-api:
    image: registry.gitlab.com/mcfitz2/lab/fitbit-api:latest
    restart: always
    build:
      context: ./
      dockerfile: ./fitbit_api/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  sms:
    image: registry.gitlab.com/mcfitz2/lab/sms:latest
    restart: always
    build:
      context: ./
      dockerfile: ./sms/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  calls:
    image: registry.gitlab.com/mcfitz2/lab/calls:latest
    restart: always
    build:
      context: ./
      dockerfile: ./calls/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  ynab:
    image: registry.gitlab.com/mcfitz2/lab/ynab:latest
    restart: always
    build:
      context: ./
      dockerfile: ynab/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  weather:
    image: registry.gitlab.com/mcfitz2/lab/weather:latest
    restart: always
    build:
      context: ./
      dockerfile: weather/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  instagram:
    image: registry.gitlab.com/mcfitz2/lab/instagram:latest
    restart: always
    build:
      context: ./
      dockerfile: ./instagram/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  stocks:
    image: registry.gitlab.com/mcfitz2/lab/stocks:latest
    restart: always
    build:
      context: ./
      dockerfile: ./stocks/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"

  gmail:
    image: registry.gitlab.com/mcfitz2/lab/gmail:latest
    restart: always
    build:
      context: ./
      dockerfile: ./gmail/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  geocoding:
    image: registry.gitlab.com/mcfitz2/lab/geocoding:latest
    restart: always
    build:
      context: ./
      dockerfile: ./geocoding/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  strava_api:
    image: registry.gitlab.com/mcfitz2/lab/strava_api:latest
    restart: always
    build:
      context: ./
      dockerfile: ./strava_api/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  db_tasks:
    image: registry.gitlab.com/mcfitz2/lab/db_tasks:latest
    restart: always
    build:
      context: ./
      dockerfile: ./db_tasks/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  wrench_a_part:
    image: registry.gitlab.com/mcfitz2/lab/wrench_a_part:latest
    restart: always
    build:
      context: ./
      dockerfile: ./wrench_a_part/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
  postgres_backup:
    image: registry.gitlab.com/mcfitz2/lab/postgres_backup:latest
    restart: always
    build:
      context: ./
      dockerfile: ./postgres_backup/Dockerfile
    environment:
      PREFECT_API_URL: "{{ lookup('bitwarden.secrets.lookup', 'fa0d0056-4ed9-46d4-b211-b202013d0a83') }}"
      PREFECT_API_KEY: "{{ lookup('bitwarden.secrets.lookup', 'a967dcc7-6410-4a51-a9e8-b202013ce6e4') }}"
