- name: Remove apparmor-utils
  ansible.builtin.apt:
    name:
      - apparmor-utils
      - apparmor
    state: absent

- name: Create config
  ansible.builtin.template:
    src: config.toml.j2
    dest: "/root/config/config.toml"
    owner: "root"
    group: "root"
    mode: "0600"


- name: Create Container
  docker_container:
    name: gitlab-runner
    state: started
    pull: true
    image: gitlab/gitlab-runner:latest
    restart_policy: always
    volumes:
      - /root/config:/etc/gitlab-runner 
      - /var/run/docker.sock:/var/run/docker.sock
