- name: Create [gitlab-runner] namespace
  kubernetes.core.k8s:
    name: gitlab-runner
    api_version: v1
    kind: Namespace
    state: present

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: gitlab
    repo_url: "https://charts.gitlab.io"
- name: Deploy gitlab-runner
  kubernetes.core.helm:
    name: gitlab-runner
    chart_ref: gitlab/gitlab-runner
    release_namespace: gitlab-runner
    wait: true
    update_repo_cache: true
    disable_hook: true
    values:
      runnerToken: "{{ gitlab_runner_token }}"
      replicas: 4
      gitlabUrl: https://gitlab.com
