- name: Create [gitlab-runner] namespace
  kubernetes.core.k8s:
    name: gitlab-runner
    api_version: v1
    kind: Namespace
    state: present

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: gitlab
    repo_url: "https://charts.gitlab.io"
- name: Deploy gitlab-runner
  kubernetes.core.helm:
    name: gitlab-runner
    chart_ref: gitlab/gitlab-runner
    release_namespace: gitlab-runner
    wait: true
    update_repo_cache: true
    disable_hook: true
    values:
      runnerToken: "{{ gitlab_runner_token }}"
      replicas: 1
      gitlabUrl: https://gitlab.com
      rbac:
        create: true
      runners:
        config: |
          [[runners]]
            [runners.kubernetes]
              namespace = "gitlab-runner"
              image = "alpine"

              [runners.kubernetes.pod_labels]
                app = "gitlab-runner"
              [runners.kubernetes.affinity]
                [[runners.kubernetes.affinity.pod_anti_affinity.preferred_during_scheduling_ignored_during_execution]]
                  weight = 100
                [runners.kubernetes.affinity.pod_anti_affinity.preferred_during_scheduling_ignored_during_execution.pod_affinity_term]
                    topology_key = "kubernetes.io/hostname"
                  [runners.kubernetes.affinity.pod_anti_affinity.preferred_during_scheduling_ignored_during_execution.pod_affinity_term.label_selector]
                    [[runners.kubernetes.affinity.pod_anti_affinity.preferred_during_scheduling_ignored_during_execution.pod_affinity_term.label_selector.match_expressions]]
                      key = "app"
                      operator = "In"
                      values = ["gitlab-runner"]
