- name: Check if helm is installed /usr/local/bin/helm
  ansible.builtin.stat:
    path: $HOME/.config/helm/repositories.yaml
  register: helm_check

- name: Download get-helm-3
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: ~/get-helm-3.sh
    mode: "700"
  when: not helm_check.stat.exists

- name: Install helm if not exist
  ansible.builtin.command: >-
    ~/get-helm-3.sh
  when: not helm_check.stat.exists
  changed_when: true

- name: Install python packages
  ansible.builtin.pip:
    name:
      - kubernetes
      - jsonpatch
      - PyYAML
    break_system_packages: true